"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^c5@a%7910yu2v7w!07z3uasydr7ll^j_%$rs3trh($zyul629'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

# Basic CSP: Only allow content from your own domain
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com") # Example: allow Google Fonts
CSP_SCRIPT_SRC = ("'self'",)

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# LibraryProject/settings.py

# --- HTTPS and SSL/TLS Settings ---

# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# Instructs the browser to only connect via HTTPS for the next year
SECURE_HSTS_SECONDS = 31536000 
# Apply HSTS to all subdomains (e.g., api.yourdomain.com)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Allows your site to be included in the browser's HSTS preload list
SECURE_HSTS_PRELOAD = True


# --- Secure Cookies ---

# Ensure session cookies are only sent over HTTPS connections
SESSION_COOKIE_SECURE = True
# Ensure CSRF cookies are only sent over HTTPS connections
CSRF_COOKIE_SECURE = True


# --- Security Headers ---

# Prevent the site from being rendered in an <iframe> (protects against Clickjacking)
X_FRAME_OPTIONS = 'DENY'

# Prevent the browser from guessing the content type (prevents MIME-sniffing)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable the browser's built-in XSS filter
SECURE_BROWSER_XSS_FILTER = True


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py
# LibraryProject/settings.py

# 1. Disable DEBUG in production to prevent leaking sensitive tracebacks
DEBUG = False

# 2. Browser-side protections against XSS and Sniffing
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'  # Prevents Clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True

# 3. Enforce HTTPS for sensitive cookies
# Note: Ensure your site is served over HTTPS before enabling these
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# 4. Secure Proxy settings (standard if behind a proxy like Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True # Redirects all HTTP requests to HTTPS

LOGIN_REDIRECT_URL = 'list_books'  # Redirect to book list after login
LOGOUT_REDIRECT_URL = 'login'      # Redirect to login page after logout
# settings.py

# Replace 'users' with whatever your app name is
# settings.py

# The format is 'app_name.ModelName'
AUTH_USER_MODEL = 'bookshelf.CustomUser'
AUTH_USER_MODEL = 'users.CustomUser'

# Ensure you have media settings configured for the profile_photo field
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'